// Customer-facing column list for building_blocks.
// The internal audit column `created_by` is intentionally excluded so that
// anonymous (public catalog) reads never expose internal admin user ids.
export const BUILDING_BLOCK_PUBLIC_COLUMNS = [
  "id",
  "slug",
  "name",
  "description",
  "short_description",
  "category",
  "block_type",
  "provider_id",
  "min_people",
  "max_people",
  "duration",
  "price_adult",
  "price_adult_note",
  "price_type",
  "price_child",
  "price_child_note",
  "price_child_min_age",
  "price_child_max_age",
  "price_pet",
  "price_pet_note",
  "is_from_price",
  "price_display_override",
  "price_extras",
  "external_url",
  "image_url",
  "image_asset",
  "is_published",
  "is_active",
  "sort_order",
  "tags",
  "seasonal_notes",
  "created_at",
  "updated_at",
  "price_includes_vat",
  "vat_rate",
  "status",
  "location_lat",
  "location_lng",
  "location_address",
  "map_activity_type_id",
  "catering_type",
  "catering_role",
  "required_with",
  "suggested_addons",
  "scaling_rules",
].join(", ");

export const BUILDING_BLOCK_PUBLIC_SELECT_WITH_PROVIDER = `${BUILDING_BLOCK_PUBLIC_COLUMNS}, provider:partners!building_blocks_provider_id_fkey(id, name, email)`;
