project_id = "blhspuifehausilnzwio"

[functions.send-quote-request]
verify_jwt = false

[functions.quote-chat]
verify_jwt = false

[functions.send-wedding-inquiry]
verify_jwt = false

[functions.send-program-request]
verify_jwt = false

[functions.invite-partner]
verify_jwt = false

[functions.select-accommodation-quote]
verify_jwt = false

[functions.send-accommodation-request]
verify_jwt = false

[functions.notify-accommodation-quote]
verify_jwt = false