/**
 * Een vast programma voor de referentiepagina /ontwerp/klantportaal en de
 * visuele regressietest (klantportaal fase 4): twee dagen, logies gekozen,
 * onderdelen in drie toestanden, facturatiegegevens nog aan te vullen.
 * Verzonnen gegevens; niets hiervan komt uit de database.
 */
import type { AccommodationQuote, AccommodationRequest } from "@/types/accommodation";
import type { ProgramRequestItem, ProgramRequestWithItems } from "@/types/programRequest";

const DAG_1 = "2026-11-05";
const DAG_2 = "2026-11-06";

const basisItem: ProgramRequestItem = {
  id: "",
  request_id: "demo-programma",
  block_id: null,
  block_name: "",
  block_category: "activity",
  provider_name: "",
  provider_id: "",
  provider_email: null,
  block_type: "partner",
  price_indication: null,
  duration: null,
  day_index: 0,
  preferred_time: null,
  customer_notes: null,
  status: "pending",
  status_note: null,
  status_updated_at: null,
  status_updated_by: null,
  version: 1,
  created_at: "2026-09-01T09:00:00Z",
  updated_at: "2026-09-01T09:00:00Z",
  executed_at: null,
  customer_accepted_at: null,
  customer_counter_time: null,
  customer_counter_note: null,
  customer_counter_at: null,
  confirmed_time: null,
  quoted_price: null,
  quoted_at: null,
  quoted_notes: null,
  proposed_time: null,
  proposed_date: null,
  image_url: null,
  image_asset: null,
  customer_approved_at: null,
  item_quote_status: "offerte_verstuurd",
  admin_price_override: null,
  admin_price_notes: null,
  skip_partner_notification: false,
  price_type: "per_person",
  external_url: null,
  override_people: null,
};

const item = (overrides: Partial<ProgramRequestItem>): ProgramRequestItem => ({ ...basisItem, ...overrides });

export const DEMO_ITEMS: ProgramRequestItem[] = [
  item({
    id: "demo-overtocht",
    block_name: "Overtocht Harlingen naar Vlieland",
    block_category: "transport",
    provider_name: "Bureau Vlieland",
    provider_id: "bureau",
    block_type: "bureau",
    duration: "1,5 uur",
    day_index: 0,
    preferred_time: "10:30",
    confirmed_time: "10:30",
    status: "confirmed",
    customer_approved_at: "2026-09-02T10:00:00Z",
    customer_accepted_at: "2026-09-02T10:00:00Z",
    quoted_price: 38.5,
    item_quote_status: "bevestigd",
    location_address: "Veerhaven, Harlingen",
  }),
  item({
    id: "demo-wadexcursie",
    block_name: "Wadexcursie met gids",
    provider_name: "Wadloopcentrum Vlieland",
    provider_id: "wadloopcentrum",
    duration: "2,5 uur",
    day_index: 0,
    preferred_time: "14:00",
    confirmed_time: "14:00",
    status: "confirmed",
    customer_approved_at: "2026-09-02T10:00:00Z",
    quoted_price: 27.5,
    quoted_at: "2026-09-03T09:00:00Z",
    item_quote_status: "bevestigd",
    block_short_description: "Te voet het wad op bij laag water, met uitleg over wat er leeft in de bodem.",
    location_address: "Havenweg 1, Vlieland",
    provider_profile: { id: "wadloopcentrum", name: "Wadloopcentrum Vlieland", address_city: "Vlieland" },
  }),
  item({
    id: "demo-diner",
    block_name: "Diner aan de lange tafel",
    block_category: "catering",
    provider_name: "Trattoria Oliva",
    provider_id: "oliva",
    duration: "2 uur",
    day_index: 0,
    preferred_time: "19:00",
    status: "pending",
    customer_approved_at: "2026-09-02T10:00:00Z",
    price_indication: "vanaf € 42,50 p.p.",
    location_address: "Dorpsstraat 61, Vlieland",
  }),
  item({
    id: "demo-fietstocht",
    block_name: "Fietstocht naar de Vliehors",
    provider_name: "Fietsverhuur Jan van Vlieland",
    provider_id: "fietsverhuur",
    duration: "3 uur",
    day_index: 1,
    preferred_time: "10:00",
    proposed_time: "10:30",
    status: "alternative",
    status_note: "Om 10:00 is de groep van de dag ervoor nog bezig; 10:30 past beter.",
    customer_approved_at: "2026-09-02T10:00:00Z",
    quoted_price: 18,
    quoted_at: "2026-09-04T09:00:00Z",
    location_address: "Dorpsstraat 1, Vlieland",
  }),
  item({
    id: "demo-lunch",
    block_name: "Lunch bij Strandpaviljoen De Zeemeeuw",
    block_category: "catering",
    provider_name: "Zelf te regelen",
    provider_id: "self",
    block_type: "self_arranged",
    day_index: 1,
    preferred_time: "13:00",
    status: "confirmed",
    external_url: "https://example.org/zeemeeuw",
  }),
];

export const DEMO_PROGRAM = {
  id: "demo-programma",
  customer_token: "demo",
  customer_name: "Mevrouw M. Swagerman",
  customer_email: "m.swagerman@example.org",
  customer_phone: "06 12345678",
  customer_company: "Scherp in Veiligheid",
  number_of_people: 12,
  selected_dates: [DAG_1, DAG_2],
  general_notes: null,
  created_at: "2026-09-01T09:00:00Z",
  updated_at: "2026-09-04T09:00:00Z",
  expires_at: "2026-12-01T00:00:00Z",
  reference_number: "BV-2609-0042",
  origin: "quote",
  quote_status: "akkoord_ontvangen",
  quote_valid_until: "2026-10-15",
  quote_sent_at: "2026-09-02T08:00:00Z",
  quote_sent_by: null,
  quote_personal_message: null,
  admin_created_by: null,
  program_description: "Twee dagen Vlieland met het team: het wad op, fietsen naar de Vliehors en samen eten.",
  program_published_at: "2026-09-02T08:00:00Z",
  billing_company_name: "Scherp in Veiligheid B.V.",
  billing_contact_name: "M. Swagerman",
  items: DEMO_ITEMS,
} as unknown as ProgramRequestWithItems;

export const DEMO_ACCOMMODATION = {
  id: "demo-logies",
  customer_token: "demo",
  customer_name: "Mevrouw M. Swagerman",
  customer_email: "m.swagerman@example.org",
  customer_phone: "06 12345678",
  customer_company: "Scherp in Veiligheid",
  reference_number: "LOG-2609-0017",
  arrival_date: DAG_1,
  departure_date: DAG_2,
  number_of_guests: 12,
  accommodation_type: "hotel",
  room_count: 6,
  room_occupancy: "double",
  room_types: ["double"],
  location_preference: ["village"],
  facilities_required: ["breakfast", "wifi"],
  budget_range: null,
  special_requests: null,
  wants_activities: true,
  linked_program_id: "demo-programma",
  status: "accepted",
  admin_notes: null,
  quotes_requested_count: 3,
  quotes_declined_count: 1,
  created_at: "2026-09-01T09:00:00Z",
  updated_at: "2026-09-05T09:00:00Z",
  expires_at: "2026-12-01T00:00:00Z",
} as unknown as AccommodationRequest;

export const DEMO_QUOTES = [
  {
    id: "demo-offerte",
    request_id: "demo-logies",
    partner_id: "zeezicht",
    accommodation_name: "Hotel Zeezicht",
    description: "Familiehotel aan de dorpsstraat, op loopafstand van het strand.",
    room_configuration: [
      { type: "double", count: 6, price_per_night: 145, occupancy: 2 },
    ],
    price_total: 1740,
    price_per_person_per_night: 72.5,
    price_includes_vat: true,
    vat_rate: 9,
    includes: ["Ontbijt", "Handdoeken en linnen", "Fietsenstalling"],
    conditions: "Annuleren tot 14 dagen voor aankomst kosteloos.",
    board_type: "breakfast",
    board_notes: null,
    valid_until: "2026-10-15",
    status: "selected",
    submitted_at: "2026-09-04T09:00:00Z",
    selected_at: "2026-09-05T09:00:00Z",
    partner_notes: null,
    quote_attachment_path: null,
    quote_attachment_filename: null,
    quote_external_url: null,
    invoiced_amount: null,
    invoiced_number: null,
    invoiced_date: null,
    invoiced_file_path: null,
    commission_percentage: null,
    commission_amount: null,
    commission_status: null,
    commission_invoiced_at: null,
    created_at: "2026-09-04T09:00:00Z",
    updated_at: "2026-09-05T09:00:00Z",
    partner: {
      id: "zeezicht",
      name: "Hotel Zeezicht",
      email: "info@example.org",
      phone: "0562 451234",
      address_street: "Dorpsstraat 10",
      address_postal: "8899 AB",
      address_city: "Vlieland",
      highlight_features: ["Aan de dorpsstraat", "Fietsenstalling", "Ontbijt met eilandproducten"],
      about_text: "Al drie generaties een familiehotel in het dorp. De kamers kijken uit op de Waddenzee of de duinen.",
    },
  },
] as unknown as AccommodationQuote[];

export const DEMO_SELECTED_DATES = [new Date(`${DAG_1}T12:00:00`), new Date(`${DAG_2}T12:00:00`)];
